<a href="https://colab.research.google.com/github/LeonBecken/Bezkrovnyi_Assignments/blob/main/Bezkrovnyi_9_1_1assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 9.1

> Replace all TODOs with your code. Do not change any other code.

In [1]:
# Do not edit this cell

import numpy as np
import pandas as pd

## Numpy

### Task 1

Create a 1D numpy array with elements [1, 2, 3, 4, 5]. Do it in two different ways.


In [2]:
res = np.array([1, 2, 3, 4, 5])

print(res)

[1 2 3 4 5]


In [3]:
res2 = res2 = np.arange(1, 6)

print(res2)

[1 2 3 4 5]


### Task 2

Create a 2D numpy array with shape (3, 5) filled with random integers between 1 and 100.

In [4]:
res3 = np.random.randint(1, 101, size=(3, 5))

print(res3)

[[29 67 98 59 95]
 [ 1 97 72 35 21]
 [59 26  9  1 53]]


### Task 3

Print the first row of array `res3`.

In [5]:
print(res3[0])

[29 67 98 59 95]


### Task 4

Access the last column of array `res3`. Assume that the array may be of any 2D shape.

In [6]:
print(res3[:, -1])

[95 21 53]


### Task 5

Find the min, max, and sum of elements of the second column of array `res3`.

In [10]:
second_col = res3[:, 1]

# Min
res_min = np.min(second_col)

print('min =', res_min)

min = 26


In [11]:
# Max
res_max = np.max(second_col)

print('max =', res_max)

max = 97


In [12]:
# Sum
res_sum = np.sum(second_col)

print('sum =', res_sum)

sum = 190


### Task 6

Tabulate the function

$$f(x) = e^{2x}$$

on interval `[0, 1]` with step 0.1.

By "tabulate" we mean that we want to have a table (1D array), where on the first position we will have the function value for 0, on the second position 0.1, and so on.

In [19]:
x = np.arange(0, 1.01, 0.1)

f_x = np.exp(2 * x)

print(f_x)

[1.         1.22140276 1.4918247  1.8221188  2.22554093 2.71828183
 3.32011692 4.05519997 4.95303242 6.04964746 7.3890561 ]


## Pandas

We will be working on the classic dataset for beginner data scientists: Titanic passengers.

### Task 7

Load the dataset from the following URL: https://web.stanford.edu/class/cs102/datasets/Titanic.csv

In [19]:
import pandas as pd
import requests

url = "https://web.stanford.edu/class/cs102/datasets/Titanic.csv"

try:
    response = requests.get(url)
    response.raise_for_status()
    df = pd.read_csv(url)
    print("Файл успішно завантажено")
except requests.exceptions.RequestException as e:
    print("Помилка при завантаженні файлу:", e)


Файл успішно завантажено


### Task 8

Let's see the series/columns present in the data frame.

Also, let's inspect the first ten rows of data.

In [ ]:
print(df.head(10))

### Task 9

Add a new column - full name - it should be a concat of the first and last name.

In [23]:
df["fullname"] = df["first"] + " " + df["last"]

print(df[["first", "last", "fullname"]].head(10))

                                        first       last  \
0                             Mr. Owen Harris     Braund   
1  Mrs. John Bradley (Florence Briggs Thayer)    Cumings   
2                                  Miss Laina  Heikkinen   
3          Mrs. Jacques Heath (Lily May Peel)   Futrelle   
4                           Mr. William Henry      Allen   
5                                   Mr. James      Moran   
6                               Mr. Timothy J   McCarthy   
7                        Master Gosta Leonard    Palsson   
8    Mrs. Oscar W (Elisabeth Vilhelmina Berg)    Johnson   
9                 Mrs. Nicholas (Adele Achem)     Nasser   

                                            fullname  
0                             Mr. Owen Harris Braund  
1  Mrs. John Bradley (Florence Briggs Thayer) Cum...  
2                               Miss Laina Heikkinen  
3        Mrs. Jacques Heath (Lily May Peel) Futrelle  
4                            Mr. William Henry Allen  
5        

### Task 10

Remove the two original columns - last, first.

In [24]:
df.drop(["first", "last"], axis=1, inplace=True)
print(df.head())

  gender   age  class     fare     embarked survived  \
0      M  22.0      3   7.2500  Southampton       no   
1      F  38.0      1  71.2833    Cherbourg      yes   
2      F  26.0      3   7.9250  Southampton      yes   
3      F  35.0      1  53.1000  Southampton      yes   
4      M  35.0      3   8.0500  Southampton       no   

                                            fullname  
0                             Mr. Owen Harris Braund  
1  Mrs. John Bradley (Florence Briggs Thayer) Cum...  
2                               Miss Laina Heikkinen  
3        Mrs. Jacques Heath (Lily May Peel) Futrelle  
4                            Mr. William Henry Allen  


### Task 11

Calculate the total number of survivors in the dataset.

In [34]:
print(df["survived"].value_counts())

total_survivors = df["survived"].value_counts().get("yes", 0)
print("Total survivors =", total_survivors)

survived
no     549
yes    342
Name: count, dtype: int64
Total survivors = 342
